### ISSUE TITLE
Questions about Looker Extension Framework Setup

### ISSUE THREAD

**Issue by satonos** [looker-open-source/dashboard-summarization#10]
1. Is it right to use "git clone git@github.com:LukaFontanilla/looker-explore-assistant.git"? It is for "Looker Explore Assistant" so I think it is right to use "git@github.com:looker-open-source/dashboard-summarization.git".
2. When I did it "npm develop", the error is happended like this.--Unknown command: "develop" I tried some commands but it's still not working.

**Comment by LukaFontanilla** [comment]
Thank you for the docs callout. We just updated the repo to reflect how to run the extension locally and the correct Repo url now that it's been migrated to open source.
