### ISSUE TITLE
bundle.js.map

### ISSUE THREAD

**Issue by satonos** [looker-open-source/dashboard-summarization#12]
Drag and drop ALL of the generated JavaScript files contained in the `dist` directory into the Looker project interface.--> How can I upload to Looker with `bundle.js.map`? The error was happend when I upload `bundle.js.map`  to Looker.

Expecting 'end_of_file', 'keyword', got '{'
And also, `bundle.js.map` is changed type of file `bundle.js.map.lkml` automaticaly.

**Comment by ryan-gould-accenture** [comment]
I have also encountered this error.  

Additionally, even when running the localhost server I am able to load a tile into the dashboard but not get any functionality.  Is there additional config that needs to take place?
![image](https://github.com/looker-open-source/dashboard-summarization/assets/168147896/bcde38d5-d24c-43c1-a01c-e4500dddf7f3)
