### ISSUE TITLE
Is it possible to add auth to the websocket-service?

### ISSUE THREAD

**Issue by karlanka** [looker-open-source/dashboard-summarization#31]
The websocket-service is set to be publicly open. Is it possible to add some sort of auth mechanism that verifies that it is the Looker extension that connects to the socket?

**Comment by LukaFontanilla** [comment]
We just added simple client secret auth to the public Cloud Run service. See this PR -> https://github.com/looker-open-source/dashboard-summarization/pull/40

Additionally in prod, the service is called from the Looker backend via an Extension method called `serverProxy` and no longer from the browser directly
