### ISSUE TITLE
Summary tile doesn't use correct user data in signed embeds

### ISSUE THREAD

**Issue by svh-cb** [looker-open-source/dashboard-summarization#37]
In our setup we are embedding dashboards into our own website using signed embeds. These signed embeds use user attributes, which are in turn used in our dashboards to pre-filter data.

When we use the summary tile in an embedded dashboard, the user attributes for the embed role that views the dashboard don't get applied to the queries the summarizer runs. Instead it seems to apply the user attributes for the user associated with the API key that it uses.

This causes an issue where the summaries are based on data that the viewer of the dashboard might not be permitted to access.

**Comment by LukaFontanilla** [comment]
We just updated the extension to run queries in the frontend (with the context of the end user) as opposed to on the backend funneled through a single service account. We've also modified the backend to run as a Restful API service that can be secure with a custom client secret -> https://github.com/looker-open-source/dashboard-summarization/pull/40

Thank you for the feedback
